name: purity
version: 0.4.0
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: Purity is a framework which allows objects to be consumed remotely via a stream of strings.
homepage: http://github.com/0xor1/purity
environment:
  sdk: '>=1.3.0+6 <2.0.0'
dependencies:
  bson: '>=0.1.15 <2.0.0'
  controls_and_panels: '>=0.1.0 <0.2.0'
  eventable: '>=3.0.3 <4.0.0'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  transmittable: '>=0.1.5 <1.0.0'
dev_dependencies:
  unittest: any
