name: purity
version: 0.0.1
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: Purity is a simple web framework for developing single page, real time web apps with web sockets. Purity hides all of the server-client communications from the developer and allows for the same app code to run completely on the client for quick and rapid testing cycles, or with a few additional lines of code split the server side and client side ready for production.
homepage: http://github.com/0xor1/purity
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  bson: '>=0.1.15 <2.0.0'
  eventable: '>=2.0.13 <3.0.0'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  transmittable: '>=0.0.17 <1.0.0'
